using ETransferServer.Common;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ETransferServer.Grains.Options;

/// <summary>
/// Configuration options for withdrawal network operations
/// Manages network-specific withdrawal parameters and validation
/// </summary>
public class WithdrawNetworkOptions
{
    /// <summary>
    /// List of network information configurations for withdrawal operations
    /// Each entry defines network-specific parameters like confirmation requirements and fees
    /// </summary>
    public List<NetWorkInfo> NetworkInfos { get; set; } = new();
    
    /// <summary>
    /// Retrieves network information for a specific network and symbol combination
    /// </summary>
    /// <param name="network">Network identifier (e.g., "Ethereum", "BSC")</param>
    /// <param name="symbol">Token symbol (e.g., "USDT", "BTC")</param>
    /// <returns>Network information configuration</returns>
    /// <exception cref="InvalidOperationException">Thrown when network-symbol combination is not supported</exception>
    public NetWorkInfo GetNetworkInfo(string network, string symbol)
    {
        var coin = GuidHelper.GenerateId(network, symbol);
        var coinInfo = NetworkInfos.FirstOrDefault(t =>
            t.Coin.Equals(coin, StringComparison.OrdinalIgnoreCase));
        AssertHelper.NotNull(coinInfo, "withdraw coin not support, coin:{Coin}", coin);
        return coinInfo;
    }
    
    /// <summary>
    /// Checks if a network and symbol combination is supported for withdrawal
    /// </summary>
    /// <param name="network">Network identifier</param>
    /// <param name="symbol">Token symbol</param>
    /// <returns>True if supported, false otherwise</returns>
    public bool IsSupported(string network, string symbol)
    {
        var coin = GuidHelper.GenerateId(network, symbol);
        return NetworkInfos.Any(t => t.Coin.Equals(coin, StringComparison.OrdinalIgnoreCase));
    }
    
    /// <summary>
    /// Gets all supported network-symbol combinations
    /// </summary>
    /// <returns>List of coin identifiers</returns>
    public List<string> GetSupportedCoins()
    {
        return NetworkInfos.Select(info => info.Coin).ToList();
    }
    
    /// <summary>
    /// Gets network information by coin identifier
    /// </summary>
    /// <param name="coinId">Coin identifier generated by GuidHelper.GenerateId</param>
    /// <returns>Network information or null if not found</returns>
    public NetWorkInfo GetNetworkInfoByCoin(string coinId)
    {
        return NetworkInfos.FirstOrDefault(t => 
            t.Coin.Equals(coinId, StringComparison.OrdinalIgnoreCase));
    }
}

/// <summary>
/// Network-specific information for withdrawal operations
/// Contains blockchain parameters and operational settings
/// </summary>
public class NetWorkInfo
{
    /// <summary>
    /// Unique coin identifier generated from network and symbol combination
    /// Format: Generated by GuidHelper.GenerateId(network, symbol)
    /// </summary>
    public string Coin { get; set; }
    
    /// <summary>
    /// Number of block confirmations required before withdrawal is considered final
    /// Higher values provide more security but longer wait times
    /// </summary>
    public int ConfirmNum { get; set; }
    
    /// <summary>
    /// Estimated time in seconds for transaction to be blocked/confirmed
    /// Used for user experience and timeout calculations
    /// </summary>
    public decimal BlockingTime { get; set; }
    
    /// <summary>
    /// Additional time in seconds to wait for extra network reliability
    /// Default: 30 seconds
    /// Used as safety buffer for network irregularities
    /// </summary>
    public int ExtraRequestTime { get; set; } = 30;
    
    /// <summary>
    /// Number of decimal places for this token on this network
    /// Used for amount formatting and validation
    /// </summary>
    public int Decimal { get; set; }
    
    /// <summary>
    /// Minimum withdrawal amount for this network-token combination
    /// Default: 0 (no minimum)
    /// Specified in token units
    /// </summary>
    public decimal Amount { get; set; } = 0;
    
    /// <summary>
    /// Fee alarm threshold percentage
    /// Default: 10%
    /// Triggers alerts when actual fees exceed this percentage of expected fees
    /// </summary>
    public decimal FeeAlarmPercent { get; set; } = 10;
    
    /// <summary>
    /// Estimated arrival time in seconds for withdrawal transactions
    /// Default: 1000 seconds (~16.7 minutes)
    /// Used for user notifications and status updates
    /// </summary>
    public int EstimatedArrivalTime { get; set; } = 1000;
    
    /// <summary>
    /// Whether this network configuration is currently active
    /// Default: true
    /// Can be used to temporarily disable withdrawals for specific networks
    /// </summary>
    public bool IsActive { get; set; } = true;
    
    /// <summary>
    /// Maximum withdrawal amount per transaction
    /// Null means no limit
    /// Used for risk management and compliance
    /// </summary>
    public decimal? MaxWithdrawAmount { get; set; }
    
    /// <summary>
    /// Daily withdrawal limit for this network-token combination
    /// Null means no limit
    /// Used for risk management and regulatory compliance
    /// </summary>
    public decimal? DailyWithdrawLimit { get; set; }
}